### ISSUE TITLE
The website does not yet describe how the two rooms will be split.

### ISSUE THREAD

**Issue by bsmith89** [bsmith89/2016-04-29-ucsf#6]

**Comment by bsmith89** [comment]
@dotsdl, @fu9ar.  When you've made a first pass at choosing a scope for your intermediate lessons, could you each draft a blurb (3 or 4 sentences, maybe) which gives some concrete examples of skills/knowledge learners should have if they plan on attending the intermediate ("advanced beginner") rooms?

**Comment by kevin-vilbig** [comment]
Intermediate users should have some prior knowledge of bash, consistent with the SWC Beginner curriculum. You can expect to learn a few more tips and tricks on top of that foundation that will give you some more options in crafting shell scripts to automate your workflow.

**Comment by dotsdl** [comment]
Are we good on this front, or is there more that needs to be done? In particular, is there something more that needs to be said about the Python split? My intention for the intermediate lesson is not to assume Python experience but to assume a background in programming, which allows me to move at a faster pace and more easily transition into higher-level concepts.

**Comment by bsmith89** [comment]
That sounds great to me.

Have you and @fu9ar settled on the shell and git lesson scope?

**Comment by kevin-vilbig** [comment]
I am not settled. Git is going to be the standard lesson. There is one knowledgable respondent on the survey so far, so I doubt we'll need to cater to that one person in any capacity. But, for bash, it seems like a good chunk of the people are already experienced with writing loops, which is pretty much the culmination of the basic bash lessons, though we only have about a 40% response rate so far....

Rather than trying to draft a curriculum, I could run through the Makefile lesson for the advanced group instead? What do y'all think about that?

**Comment by dotsdl** [comment]
@fu9ar I think it's better to err on the side of assuming too little than assuming too much, since though many respondents said they could write a loop, most respondents said they could not pipe commands together. People generally pick up these skills in pieces, so it's dangerous to assume that their (stated) ability to write a loop (in the abstract) means that they would learn little from the rest of the shell lesson.

I think the better thing to do might be to teach the shell lesson as it is, but try to test the pace a bit especially at the beginning, and don't dawdle on too many challenge/breakout questions. Resist the urge to go faster, but gauge the room given the pace you're setting. In my experience it's rare to see the shell lesson covered completely (all the way through scripting, use of find), but this might be a case where you can do that to great effect in 3 hours time.

**Comment by bsmith89** [comment]
:+1:

**Comment by dotsdl** [comment]
@fu9ar I usually prepare a git repo with all the directories/files the participants will need (such as [this one](https://github.com/dotsdl/swc_asuphysics_data)), and I have them clone this before we begin on the first day. In addition to getting them everything they need for the workshop, it tests 1) that they have a working shell, and 2) that they have a working version of git. We can then immediately troubleshoot issues on these and save ourselves the time later.

I'll go ahead and make one like the example I linked; I'll add you as a collaborator so you can push any changes you want to the bash lesson materials.

I shamelessly stole this practice from @jduckles.

**Comment by dotsdl** [comment]
@fu9ar added data repo [here](https://github.com/dotsdl/swc_ucsf_intermediate_data). Haven't updated anything yet from novice lessons, including python stuff. Feel free to do anything you want with the shell materials.

**Comment by kevin-vilbig** [comment]
Okay. That's why I brought it up here rather than acting unilaterally. Thx for the feedback. I think I'll have people download the filesn normally. It should be relatively straightforward.

**Comment by bsmith89** [comment]
_De facto_ resolved.
